#!/bin/bash
# https://github.com/pinterest/ktlint pre-commit hook
echo "Running ktlint"
git diff --name-only --cached --relative --diff-filter=ACMT "*.kt" "*.kts" | xargs -0 ./ktlint --relative --format
if [ $? -ne 0 ]; then
  echo "ktlint check failed"
  exit 1
else
  echo "ktlint check passed"
  git diff --name-only --cached --relative --diff-filter=ACMT "*.kt" "*.kts" | xargs -0 git add
fi